/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.Weight.Parabolic
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.CommonKernel.Basic
public import TauCeti.Algebra.AlgebraicGroup.Representation.Coordinate
public import TauCeti.Algebra.HopfAlgebra.HopfIdeal.Map
public import TauCeti.Algebra.Coalgebra.Subcomodule.Coordinate

/-!
# Split flags for generated affine group schemes

A based representation preserves its decreasing weight filtration exactly when its coefficient
matrix is block triangular. This file expresses the same condition for the closed subgroup scheme
generated by a family of morphisms: the image of the weight-parabolic ideal under the
representation's coordinate morphism lies in the family's common-kernel Hopf ideal exactly when
every member of the family has block-triangular coefficient matrix.

This is entirely scheme theoretic. It makes no assertion about density of algebra-valued points.

## Main declaration

* `TauCeti.Comodule.weightParabolic_map_coordinateBialgHom_le_commonKernel_iff`: a family of
  generators preserves a split weighted flag exactly when the generated closed subgroup scheme
  does.
* `TauCeti.Comodule.coefficientMatrix_commonKernelQuotient_blockTriangular`: the representation
  corestricted to the generated group's coordinate algebra has block-triangular coefficient
  matrix.
-/

public section

namespace TauCeti.Comodule

open CategoryTheory

universe u v w x

noncomputable section

variable {R : Type u} [CommRing R]
variable {H : _root_.CommHopfAlgCat.{v} R}
variable {M : Type w} [AddCommMonoid M] [Module R M] [Comodule R H M]
variable {n : ℕ} {ι : Type x} {K : ι → _root_.CommHopfAlgCat.{v} R}

/-- The image of the weight-parabolic ideal under a representation's coordinate morphism lies in
the common-kernel ideal of a family precisely when every member of the family makes the
coefficient matrix block triangular.

Contravariantly, the right side says that every generating subgroup scheme preserves the split
decreasing weight filtration, while the left side says the closed subgroup scheme they generate
does so. -/
theorem weightParabolic_map_coordinateBialgHom_le_commonKernel_iff
    (f : ∀ a, H ⟶ K a) (b : Module.Basis (Fin n) R M) (weight : Fin n → ℤ) :
    (GeneralLinear.weightParabolicDefiningHopfIdeal R weight).map
        (coordinateBialgHom (H := H) b) ≤
        CommHopfAlgCat.commonKernelHopfIdeal f ↔
      ∀ a, ((coefficientMatrix (C := H) b).map (f a).hom).BlockTriangular
        (OrderDual.toDual ∘ weight) := by
  rw [CommHopfAlgCat.le_commonKernelHopfIdeal_iff]
  constructor
  · intro h a i j hij
    change weight i < weight j at hij
    change (f a).hom (coefficientMatrix (C := H) b i j) = 0
    have hx :
        GeneralLinear.coordinateHopfAlgebraAlgEquiv R n
            (GeneralLinear.coordinateRingMap R n (MvPolynomial.X (i, j))) ∈
          GeneralLinear.weightParabolicDefiningHopfIdeal R weight := by
      apply HopfIdeal.mem_toIdeal.mp
      rw [GeneralLinear.weightParabolicDefiningHopfIdeal_toIdeal]
      exact Ideal.subset_span (GeneralLinear.X_mem_weightParabolicRelationSet R weight hij)
    have hmap := HopfIdeal.mem_map_of_mem (coordinateBialgHom (H := H) b) hx
    have hzero := RingHom.mem_ker.mp (h a (HopfIdeal.mem_toIdeal.mpr hmap))
    rw [coordinateBialgHom_X] at hzero
    simpa only [AlgHom.toRingHom_eq_coe, RingHom.coe_coe, BialgHom.coe_toAlgHom] using hzero
  · intro h a
    rw [HopfIdeal.map_toIdeal, Ideal.map_le_iff_le_comap,
      GeneralLinear.weightParabolicDefiningHopfIdeal_toIdeal]
    apply Ideal.span_le.2
    intro x hx
    rw [GeneralLinear.mem_weightParabolicRelationSet_iff] at hx
    obtain ⟨i, j, hij, rfl⟩ := hx
    apply Ideal.mem_comap.mpr
    apply RingHom.mem_ker.mpr
    simp only [AlgHom.toRingHom_eq_coe, RingHom.coe_coe, BialgHom.coe_toAlgHom,
      coordinateBialgHom_X]
    exact h a (OrderDual.toDual_lt_toDual.mpr hij)

/-- If every member of a family has block-triangular coefficient matrix, then so does the
representation corestricted to the common-kernel quotient, the coordinate algebra of the closed
subgroup scheme generated by that family. Consequently, `weightCoordinateSpanSubcomodule`
constructs every step of the split decreasing weight filtration as a subcomodule over the
generated group. -/
theorem coefficientMatrix_commonKernelQuotient_blockTriangular
    (f : ∀ a, H ⟶ K a) (b : Module.Basis (Fin n) R M) (weight : Fin n → ℤ)
    (h : ∀ a, ((coefficientMatrix (C := H) b).map (f a).hom).BlockTriangular
      (OrderDual.toDual ∘ weight)) :
    let J := CommHopfAlgCat.commonKernelHopfIdeal f
    letI : Comodule R (CommHopfAlgCat.quotient H J) M :=
      Corestrict (CommHopfAlgCat.mkQuotient H J).hom.toCoalgHom
    (coefficientMatrix (C := CommHopfAlgCat.quotient H J) b).BlockTriangular
      (OrderDual.toDual ∘ weight) := by
  dsimp only
  let J := CommHopfAlgCat.commonKernelHopfIdeal f
  let q := CommHopfAlgCat.mkQuotient H J
  let _ : Comodule R (CommHopfAlgCat.quotient H J) M := Corestrict q.hom.toCoalgHom
  rw [coefficientMatrix_corestrict]
  intro i j hij
  rw [Matrix.map_apply]
  apply (CommHopfAlgCat.mkQuotient_eq_zero_iff H J _).mpr
  apply HopfIdeal.mem_toIdeal.mpr
  have hle :
      (GeneralLinear.weightParabolicDefiningHopfIdeal R weight).map
          (coordinateBialgHom (H := H) b) ≤ J :=
    (weightParabolic_map_coordinateBialgHom_le_commonKernel_iff f b weight).mpr h
  apply hle
  rw [← coordinateBialgHom_X]
  apply HopfIdeal.mem_map_of_mem
  apply HopfIdeal.mem_toIdeal.mp
  rw [GeneralLinear.weightParabolicDefiningHopfIdeal_toIdeal]
  exact Ideal.subset_span (GeneralLinear.X_mem_weightParabolicRelationSet R weight
    (OrderDual.toDual_lt_toDual.mp hij))

end

end TauCeti.Comodule
