/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Lie.BaseChange
public import TauCeti.Algebra.Lie.F4.ShortRoot.ChevalleyAction
public import TauCeti.Algebra.Lie.Weights.Root.IntegralBasis

/-!
# The modular short-root coordinate space in type F₄

This file reduces the integral Chevalley lattice attached to the chosen rational F₄ Chevalley
system modulo two. Its base-changed root--simple-coroot basis retains the integral root labels.
The distinguished coordinate subspace is spanned by the twenty-four short-root vectors and the
two short simple coroots.

The subspace is defined only after reduction modulo two. Its integral coordinate span is not a Lie
ideal: a short--short bracket can be twice a long-root vector.

This is the full integral Chevalley lattice reduced modulo two. In this characteristic it must
not be replaced by the Lie algebra generated by the reductions of the simple generators: taking
the generated image and reducing the full integral lattice need not commute.

The short-root ideal and its complementary quotient supply the structural prerequisite for the
F₄ carrier special isogeny required by `TauCetiRoadmap/CFSGStatement/README.md`, L0 and L2.
-/

public section

namespace TauCeti.DynkinType

open _root_.LieAlgebra _root_.LieAlgebra.IsKilling LieModule Module Set
open scoped TensorProduct

noncomputable section

/-- The base of the Killing root system selected by the distinguished F₄ Lie-algebra basis. -/
abbrev f4KillingBase := (F4.lieBasis valid_F4).base

/-- The integral Chevalley Lie lattice for the chosen F₄ root-vector system. -/
abbrev f4ChevalleyLieLattice : LieSubalgebra ℤ (F4.lieAlgebra valid_F4) :=
  f4ChevalleyRootVector_isChevalleySystem.chevalleyLieLattice

/-- Integral Chevalley coordinates: one coordinate for every root and one for every simple
coroot. -/
abbrev f4ChevalleyIndex :=
  (F4.cartanSubalgebra valid_F4).root ⊕ f4KillingBase.support

/-- The root-vector--simple-coroot basis of the integral F₄ Chevalley lattice. -/
noncomputable def f4ChevalleyBasis :
    Basis f4ChevalleyIndex ℤ f4ChevalleyLieLattice :=
  f4ChevalleyRootVector_isChevalleySystem.rootSimpleCorootBasis f4KillingBase

/-- The Chevalley lattice reduced modulo two. -/
abbrev f4ModularChevalleyLieAlgebra :=
  ZMod 2 ⊗[ℤ] f4ChevalleyLieLattice

/-- The integral root--simple-coroot coordinates, retained after reduction modulo two. -/
noncomputable def f4ModularChevalleyBasis :
    Basis f4ChevalleyIndex (ZMod 2) f4ModularChevalleyLieAlgebra :=
  f4ChevalleyBasis.baseChange (ZMod 2)

/-- A root vector as an element of the integral Chevalley lattice. -/
noncomputable def f4IntegralRootVector (i : Fin 48) : f4ChevalleyLieLattice :=
  f4ChevalleyBasis (Sum.inl (f4KillingRootLabel i))

/-- A root vector in the Chevalley lattice reduced modulo two. -/
@[expose] noncomputable def f4ModularRootVector (i : Fin 48) :
    f4ModularChevalleyLieAlgebra :=
  f4ModularChevalleyBasis (Sum.inl (f4KillingRootLabel i))

/-- The coroot of a pinned root as an element of the integral Chevalley lattice. -/
noncomputable def f4IntegralCoroot (i : Fin 48) : f4ChevalleyLieLattice :=
  ⟨((coroot (f4KillingRoot i) : F4.cartanSubalgebra valid_F4) :
      F4.lieAlgebra valid_F4),
    f4ChevalleyRootVector_isChevalleySystem.coroot_mem_chevalleyLieLattice _⟩

/-- A simple coroot as a named integral Chevalley basis vector. -/
noncomputable def f4IntegralSimpleCoroot (i : Fin F4.rank) : f4ChevalleyLieLattice :=
  f4ChevalleyBasis (Sum.inr ((F4.lieBasis valid_F4).baseSupportEquiv i))

/-- A simple coroot basis vector after reduction modulo two. -/
@[expose] noncomputable def f4ModularSimpleCoroot (i : Fin F4.rank) :
    f4ModularChevalleyLieAlgebra :=
  f4ModularChevalleyBasis (Sum.inr ((F4.lieBasis valid_F4).baseSupportEquiv i))

/-- An arbitrary coroot after reduction modulo two. -/
noncomputable def f4ModularCoroot (i : Fin 48) : f4ModularChevalleyLieAlgebra :=
  1 ⊗ₜ[ℤ] f4IntegralCoroot i

theorem f4ModularRootVector_eq_basis (i : Fin 48) :
    f4ModularRootVector i =
      f4ModularChevalleyBasis (Sum.inl (f4KillingRootLabel i)) := rfl

@[simp] theorem f4ModularSimpleCoroot_eq_basis (i : Fin F4.rank) :
    f4ModularSimpleCoroot i =
      f4ModularChevalleyBasis
        (Sum.inr ((F4.lieBasis valid_F4).baseSupportEquiv i)) := rfl

@[simp] theorem coe_f4IntegralRootVector (i : Fin 48) :
    (f4IntegralRootVector i : F4.lieAlgebra valid_F4) =
      f4ChevalleyRootVector (f4KillingRoot i) := by
  rw [f4IntegralRootVector, f4ChevalleyBasis,
    IsChevalleySystem.coe_rootSimpleCorootBasis_inl]

@[simp] theorem coe_f4IntegralSimpleCoroot (i : Fin F4.rank) :
    (f4IntegralSimpleCoroot i : F4.lieAlgebra valid_F4) =
      ((coroot ((((F4.lieBasis valid_F4).baseSupportEquiv i :
        (F4.cartanSubalgebra valid_F4).root) :
          Weight ℚ (F4.cartanSubalgebra valid_F4) (F4.lieAlgebra valid_F4))) :
        F4.cartanSubalgebra valid_F4) : F4.lieAlgebra valid_F4) := by
  simp only [f4IntegralSimpleCoroot, f4ChevalleyBasis,
    IsChevalleySystem.coe_rootSimpleCorootBasis_inr]

theorem f4ModularRootVector_eq (i : Fin 48) :
    f4ModularRootVector i = 1 ⊗ₜ[ℤ] f4IntegralRootVector i := by
  rw [f4ModularRootVector, f4ModularChevalleyBasis, Basis.baseChange_apply]
  rfl

theorem f4ModularSimpleCoroot_eq (i : Fin F4.rank) :
    f4ModularSimpleCoroot i = 1 ⊗ₜ[ℤ] f4IntegralSimpleCoroot i := by
  simpa only [f4ModularSimpleCoroot, f4ModularChevalleyBasis,
    f4IntegralSimpleCoroot] using
      Module.Basis.baseChange_apply (ZMod 2) f4ChevalleyBasis
        (Sum.inr ((F4.lieBasis valid_F4).baseSupportEquiv i))

/-- A simple integral coroot acts on an integral root vector by the pinned Cartan integer. -/
theorem f4Integral_lie_simpleCoroot_rootVector (i : Fin F4.rank) (α : Fin 48) :
    ⁅f4IntegralSimpleCoroot i, f4IntegralRootVector α⁆ =
      f4SimplyConnectedRootDatum.pairing α (Fin.castAdd 44 (Fin.cast rank_F4 i)) •
        f4IntegralRootVector α := by
  apply Subtype.ext
  change ⁅(f4IntegralSimpleCoroot i : F4.lieAlgebra valid_F4),
      (f4IntegralRootVector α : F4.lieAlgebra valid_F4)⁆ =
    ((f4SimplyConnectedRootDatum.pairing α (Fin.castAdd 44 (Fin.cast rank_F4 i)) •
      f4IntegralRootVector α : f4ChevalleyLieLattice) : F4.lieAlgebra valid_F4)
  rw [show ((f4SimplyConnectedRootDatum.pairing α
      (Fin.castAdd 44 (Fin.cast rank_F4 i)) •
        f4IntegralRootVector α : f4ChevalleyLieLattice) : F4.lieAlgebra valid_F4) =
      f4SimplyConnectedRootDatum.pairing α (Fin.castAdd 44 (Fin.cast rank_F4 i)) •
        (f4IntegralRootVector α : F4.lieAlgebra valid_F4) by rfl]
  simp only [f4IntegralSimpleCoroot, f4ChevalleyBasis,
    IsChevalleySystem.coe_rootSimpleCorootBasis_inr, coe_f4IntegralRootVector]
  simpa only [f4RootCartanWeight_simple, Int.cast_smul_eq_zsmul] using
    f4ChevalleyRootVector_isChevalleySystem.toIsSl2System.lie_coroot_rootVector
      (((F4.lieBasis valid_F4).baseSupportEquiv i :
        (F4.cartanSubalgebra valid_F4).root) :
          Weight ℚ (F4.cartanSubalgebra valid_F4) (F4.lieAlgebra valid_F4))
      (f4KillingRoot α)

/-- A modular simple coroot acts on a modular root vector by the reduced pinned Cartan integer. -/
theorem f4Modular_lie_simpleCoroot_rootVector (i : Fin F4.rank) (α : Fin 48) :
    ⁅f4ModularSimpleCoroot i, f4ModularRootVector α⁆ =
      (f4SimplyConnectedRootDatum.pairing α
        (Fin.castAdd 44 (Fin.cast rank_F4 i)) : ZMod 2) • f4ModularRootVector α := by
  rw [f4ModularSimpleCoroot_eq, f4ModularRootVector_eq,
    LieAlgebra.ExtendScalars.bracket_tmul, one_mul,
    f4Integral_lie_simpleCoroot_rootVector, TensorProduct.tmul_smul,
    TensorProduct.smul_tmul']
  exact congrArg (· ⊗ₜ[ℤ] f4IntegralRootVector α)
    (Int.cast_smul_eq_zsmul (ZMod 2)
      (f4SimplyConnectedRootDatum.pairing α (Fin.castAdd 44 (Fin.cast rank_F4 i)))
      (1 : ZMod 2)).symm

/-- Integral coroot coordinates in the Chevalley basis are the pinned coroot coordinates. -/
theorem f4IntegralCoroot_eq_sum_simple (β : Fin 48) :
    f4IntegralCoroot β = ∑ i : Fin F4.rank,
      f4Coroot β (Fin.cast rank_F4 i) • f4IntegralSimpleCoroot i := by
  apply Subtype.ext
  have h := congrArg
    (fun y : F4.cartanSubalgebra valid_F4 => (y : F4.lieAlgebra valid_F4))
    (f4KillingCoroot_eq_sum_simple β)
  convert h using 1
  · simp only [f4IntegralCoroot, rootSystem_coroot_apply]
  · let u : Fin F4.rank → F4.lieAlgebra valid_F4 := fun i =>
      f4ChevalleyLieLattice.toSubmodule.subtype
        (f4Coroot β (Fin.cast rank_F4 i) • f4IntegralSimpleCoroot i)
    let v : Fin F4.rank → F4.lieAlgebra valid_F4 := fun i =>
      (F4.cartanSubalgebra valid_F4).incl
        ((F4.rationalRootSystem valid_F4).coroot (f4RootIndex β) i •
          (rootSystem (F4.cartanSubalgebra valid_F4)).coroot
            ((F4.lieBasis valid_F4).baseSupportEquiv i))
    have huv (i : Fin F4.rank) : u i = v i := by
      have hcoeff :
          (f4Coroot β (Fin.cast rank_F4 i) : ℚ) =
            (F4.rationalRootSystem valid_F4).coroot (f4RootIndex β) i := by
        rw [coroot_rationalRootSystem, simplyConnectedRootDatum_F4,
          f4SimplyConnectedRootDatum_coroot]
        congr 1
      dsimp only [u, v]
      change f4Coroot β (Fin.cast rank_F4 i) •
          (f4IntegralSimpleCoroot i : F4.lieAlgebra valid_F4) =
        (F4.rationalRootSystem valid_F4).coroot (f4RootIndex β) i •
          (((rootSystem (F4.cartanSubalgebra valid_F4)).coroot
            ((F4.lieBasis valid_F4).baseSupportEquiv i) :
              F4.cartanSubalgebra valid_F4) : F4.lieAlgebra valid_F4)
      simp only [f4IntegralSimpleCoroot, f4ChevalleyBasis,
        IsChevalleySystem.coe_rootSimpleCorootBasis_inr, rootSystem_coroot_apply]
      let w : F4.lieAlgebra valid_F4 :=
        ((coroot (((F4.lieBasis valid_F4).baseSupportEquiv i :
          (F4.cartanSubalgebra valid_F4).root) :
            Weight ℚ (F4.cartanSubalgebra valid_F4) (F4.lieAlgebra valid_F4)) :
              F4.cartanSubalgebra valid_F4) : F4.lieAlgebra valid_F4)
      change f4Coroot β (Fin.cast rank_F4 i) • w =
        (F4.rationalRootSystem valid_F4).coroot (f4RootIndex β) i • w
      calc
        _ = (f4Coroot β (Fin.cast rank_F4 i) : ℚ) • w :=
          (Int.cast_smul_eq_zsmul ℚ _ _).symm
        _ = _ := congrArg (· • w) hcoeff
    change f4ChevalleyLieLattice.toSubmodule.subtype
        (∑ i : Fin F4.rank,
          f4Coroot β (Fin.cast rank_F4 i) • f4IntegralSimpleCoroot i) =
      (F4.cartanSubalgebra valid_F4).incl
        (∑ i : Fin F4.rank,
          (F4.rationalRootSystem valid_F4).coroot (f4RootIndex β) i •
            (rootSystem (F4.cartanSubalgebra valid_F4)).coroot
              ((F4.lieBasis valid_F4).baseSupportEquiv i))
    calc
      _ = ∑ i : Fin F4.rank, u i :=
        map_sum f4ChevalleyLieLattice.toSubmodule.subtype _ Finset.univ
      _ = ∑ i : Fin F4.rank, v i := by
        apply Finset.sum_congr rfl
        intro i _
        exact huv i
      _ = _ := (map_sum (F4.cartanSubalgebra valid_F4).incl _ Finset.univ).symm

/-- Reduction modulo two preserves the pinned simple-coroot coordinate expansion. -/
theorem f4ModularCoroot_eq_sum_simple (β : Fin 48) :
    f4ModularCoroot β = ∑ i : Fin F4.rank,
      (f4Coroot β (Fin.cast rank_F4 i) : ZMod 2) • f4ModularSimpleCoroot i := by
  rw [f4ModularCoroot, f4IntegralCoroot_eq_sum_simple, TensorProduct.tmul_sum]
  apply Finset.sum_congr rfl
  intro i _
  rw [f4ModularSimpleCoroot_eq, TensorProduct.tmul_smul]
  exact congrArg (· ⊗ₜ[ℤ] f4IntegralSimpleCoroot i)
    (Int.cast_smul_eq_zsmul (ZMod 2) _ 1).symm

/-- The modular coroot at a pinned simple-root index is the corresponding simple-coroot basis
vector. -/
@[simp] theorem f4ModularCoroot_castAdd (i : Fin 4) :
    f4ModularCoroot (Fin.castAdd 44 i) =
      f4ModularSimpleCoroot (Fin.cast rank_F4.symm i) := by
  rw [f4ModularCoroot_eq_sum_simple, f4Coroot_castAdd]
  simp only [Pi.single_apply]
  rw [Finset.sum_eq_single (Fin.cast rank_F4.symm i)]
  · simp
  · intro j _ hj
    have hcast : Fin.cast rank_F4 j ≠ i := by
      intro hij
      apply hj
      apply Fin.cast_injective rank_F4
      simpa using hij
    split_ifs with hji
    · exact (hcast hji).elim
    · rw [Int.cast_zero, zero_smul]
  · intro h
    have hm : Fin.cast rank_F4.symm i ∈ Finset.univ := Finset.mem_univ _
    exact (h hm).elim

/-- In characteristic two the coroot at the negative of a pinned simple root is represented by
the same simple-coroot basis vector. -/
@[simp] theorem f4ModularCoroot_addNat_castAdd (i : Fin 4) :
    f4ModularCoroot (Fin.addNat (Fin.castAdd 20 i) 24) =
      f4ModularSimpleCoroot (Fin.cast rank_F4.symm i) := by
  rw [f4ModularCoroot_eq_sum_simple, f4Coroot_addNat]
  have hi : Fin.castAdd 24 (Fin.castAdd 20 i) = Fin.castAdd 44 i := by rfl
  rw [hi, f4Coroot_castAdd]
  simp only [Pi.neg_apply, Pi.single_apply, Int.cast_neg]
  rw [Finset.sum_eq_single (Fin.cast rank_F4.symm i)]
  · simp
  · intro j _ hj
    have hcast : Fin.cast rank_F4 j ≠ i := by
      intro hij
      apply hj
      apply Fin.cast_injective rank_F4
      simpa using hij
    split_ifs with hji
    · exact (hcast hji).elim
    · rw [Int.cast_zero, neg_zero, zero_smul]
  · intro h
    have hm : Fin.cast rank_F4.symm i ∈ Finset.univ := Finset.mem_univ _
    exact (h hm).elim

/-- The exact integral root-edge bracket inherited by the Chevalley lattice. -/
theorem f4Integral_lie_rootVector_of_add (α β γ : Fin 48)
    (h : f4SimplyConnectedRootDatum.root γ =
      f4SimplyConnectedRootDatum.root β + f4SimplyConnectedRootDatum.root α) :
    ∃ z : ℤ,
      z.natAbs = f4SimplyConnectedRootDatum.chainBotCoeff α β + 1 ∧
      ⁅f4IntegralRootVector α, f4IntegralRootVector β⁆ = z • f4IntegralRootVector γ := by
  obtain ⟨z, hz, hlie⟩ := f4_lie_rootVector_of_add α β γ h
  refine ⟨z, hz, ?_⟩
  apply Subtype.ext
  change ⁅(f4IntegralRootVector α : F4.lieAlgebra valid_F4),
      (f4IntegralRootVector β : F4.lieAlgebra valid_F4)⁆ =
    ((z • f4IntegralRootVector γ : f4ChevalleyLieLattice) :
      F4.lieAlgebra valid_F4)
  rw [show ((z • f4IntegralRootVector γ : f4ChevalleyLieLattice) :
      F4.lieAlgebra valid_F4) = z •
        (f4IntegralRootVector γ : F4.lieAlgebra valid_F4) by rfl]
  simp only [coe_f4IntegralRootVector]
  simpa only [Int.cast_smul_eq_zsmul] using hlie

/-- Every modular root-edge bracket is the reduction of its exact integral Chevalley
coefficient. -/
theorem f4Modular_lie_rootVector_of_add (α β γ : Fin 48)
    (h : f4SimplyConnectedRootDatum.root γ =
      f4SimplyConnectedRootDatum.root β + f4SimplyConnectedRootDatum.root α) :
    ∃ z : ℤ,
      z.natAbs = f4SimplyConnectedRootDatum.chainBotCoeff α β + 1 ∧
      ⁅f4ModularRootVector α, f4ModularRootVector β⁆ =
        (z : ZMod 2) • f4ModularRootVector γ := by
  obtain ⟨z, hz, hlie⟩ := f4Integral_lie_rootVector_of_add α β γ h
  refine ⟨z, hz, ?_⟩
  rw [f4ModularRootVector_eq, f4ModularRootVector_eq, f4ModularRootVector_eq,
    LieAlgebra.ExtendScalars.bracket_tmul, one_mul, hlie,
    TensorProduct.tmul_smul, TensorProduct.smul_tmul']
  exact congrArg (· ⊗ₜ[ℤ] f4IntegralRootVector γ)
    (Int.cast_smul_eq_zsmul (ZMod 2) z (1 : ZMod 2)).symm

/-- A root edge with zero descending coefficient has unit modular bracket coefficient; its
integral sign disappears modulo two. -/
theorem f4Modular_lie_rootVector_of_add_of_chainBotCoeff_eq_zero (α β γ : Fin 48)
    (h : f4SimplyConnectedRootDatum.root γ =
      f4SimplyConnectedRootDatum.root β + f4SimplyConnectedRootDatum.root α)
    (hbot : f4SimplyConnectedRootDatum.chainBotCoeff α β = 0) :
    ⁅f4ModularRootVector α, f4ModularRootVector β⁆ = f4ModularRootVector γ := by
  obtain ⟨z, hz, hlie⟩ := f4Modular_lie_rootVector_of_add α β γ h
  rw [hbot] at hz
  have hzmod : (z : ZMod 2) = 1 := by
    rw [← ZMod.natAbs_mod_two, hz]
    norm_num
  rw [hlie, hzmod, one_smul]

/-- Along a root edge between two short-root coordinates, the modular Chevalley bracket is the
target short-root vector. -/
theorem f4Modular_lie_rootVector_of_add_eq_short (α β γ : Fin 48)
    (hβ : f4Length β = 1) (hγ : f4Length γ = 1)
    (h : f4SimplyConnectedRootDatum.root γ =
      f4SimplyConnectedRootDatum.root β + f4SimplyConnectedRootDatum.root α) :
    ⁅f4ModularRootVector α, f4ModularRootVector β⁆ = f4ModularRootVector γ := by
  exact f4Modular_lie_rootVector_of_add_of_chainBotCoeff_eq_zero α β γ h
    (f4_chainBotCoeff_eq_zero_of_add_eq_short α β γ hβ hγ h)

/-- Modular root vectors bracket to zero when their rational root-space sum is absent. -/
theorem f4Modular_lie_rootVector_eq_zero_of_rootSpace_add_eq_bot (α β : Fin 48)
    (hbot : rootSpace (F4.cartanSubalgebra valid_F4)
      ((f4KillingRoot α : (F4.cartanSubalgebra valid_F4) → ℚ) + f4KillingRoot β) = ⊥) :
    ⁅f4ModularRootVector α, f4ModularRootVector β⁆ = 0 := by
  have hlie : ⁅f4ChevalleyRootVector (f4KillingRoot α),
      f4ChevalleyRootVector (f4KillingRoot β)⁆ = 0 :=
    f4ChevalleyRootVector_isChevalleySystem.toIsSl2System
      |>.lie_eq_zero_of_rootSpace_add_eq_bot (f4KillingRoot α) (f4KillingRoot β) hbot
  have hlieIntegral :
      ⁅f4IntegralRootVector α, f4IntegralRootVector β⁆ = 0 := by
    apply Subtype.ext
    change ⁅(f4IntegralRootVector α : F4.lieAlgebra valid_F4),
        (f4IntegralRootVector β : F4.lieAlgebra valid_F4)⁆ = 0
    simpa only [coe_f4IntegralRootVector] using hlie
  rw [f4ModularRootVector_eq, f4ModularRootVector_eq,
    LieAlgebra.ExtendScalars.bracket_tmul, one_mul, hlieIntegral,
    TensorProduct.tmul_zero]

/-- Recover the pinned integral root label of a Killing root. -/
abbrev f4PinnedRootIndex (α : (F4.cartanSubalgebra valid_F4).root) : Fin 48 :=
  Fin.cast numRoots_F4
    ((F4.rationalRootSystemEquiv valid_F4).indexEquiv.symm α)

@[simp] theorem f4KillingRootLabel_f4PinnedRootIndex
    (α : (F4.cartanSubalgebra valid_F4).root) :
    f4KillingRootLabel (f4PinnedRootIndex α) = α := by
  simp only [f4KillingRootLabel, f4PinnedRootIndex, f4RootIndex, Fin.cast_cast,
    Fin.cast_eq_self]
  exact Equiv.apply_symm_apply (F4.rationalRootSystemEquiv valid_F4).indexEquiv α

@[simp] theorem f4PinnedRootIndex_f4KillingRootLabel (i : Fin 48) :
    f4PinnedRootIndex (f4KillingRootLabel i) = i := by
  apply Fin.ext
  simp only [f4PinnedRootIndex, f4KillingRootLabel, f4RootIndex, Equiv.symm_apply_apply]
  rfl

@[simp] theorem f4ModularChevalleyBasis_inl_eq_rootVector
    (α : (F4.cartanSubalgebra valid_F4).root) :
    f4ModularChevalleyBasis (Sum.inl α) =
      f4ModularRootVector (f4PinnedRootIndex α) := by
  rw [f4ModularRootVector_eq_basis, f4KillingRootLabel_f4PinnedRootIndex]

/-- The pinned index of the root opposite to `α`. -/
abbrev f4OppositeRootIndex (α : Fin 48) : Fin 48 :=
  f4PinnedRootIndex (-f4KillingRootLabel α)

theorem f4KillingRootLabel_f4OppositeRootIndex (α : Fin 48) :
    f4KillingRootLabel (f4OppositeRootIndex α) = -f4KillingRootLabel α := by
  exact f4KillingRootLabel_f4PinnedRootIndex (-f4KillingRootLabel α)

theorem f4KillingRoot_injective : Function.Injective f4KillingRoot := by
  intro α β h
  have hlabel : f4KillingRootLabel α = f4KillingRootLabel β := by
    apply Subtype.ext
    exact h
  rw [← f4PinnedRootIndex_f4KillingRootLabel α,
    ← f4PinnedRootIndex_f4KillingRootLabel β, hlabel]

@[simp] theorem f4KillingRoot_f4OppositeRootIndex (α : Fin 48) :
    f4KillingRoot (f4OppositeRootIndex α) = -f4KillingRoot α := by
  exact congrArg
    (fun r : (F4.cartanSubalgebra valid_F4).root =>
      (r : Weight ℚ (F4.cartanSubalgebra valid_F4) (F4.lieAlgebra valid_F4)))
    (f4KillingRootLabel_f4OppositeRootIndex α)

@[simp] theorem f4OppositeRootIndex_involutive (α : Fin 48) :
    f4OppositeRootIndex (f4OppositeRootIndex α) = α := by
  apply f4KillingRoot_injective
  simp

/-- In the pinned F₄ table the root opposite to a simple root is the corresponding entry in the
second half of the table. -/
@[simp] theorem f4OppositeRootIndex_castAdd (i : Fin 4) :
    f4OppositeRootIndex (Fin.castAdd 44 i) =
      Fin.addNat (Fin.castAdd 20 i) 24 := by
  apply f4KillingRoot_injective
  rw [f4KillingRoot_f4OppositeRootIndex]
  have hroot : f4SimplyConnectedRootDatum.root (Fin.addNat (Fin.castAdd 20 i) 24) =
      f4SimplyConnectedRootDatum.root (Fin.castAdd 44 i) +
        (-2 : ℤ) • f4SimplyConnectedRootDatum.root (Fin.castAdd 44 i) := by
    simp only [f4SimplyConnectedRootDatum_root]
    rw [f4Root_addNat]
    have hi : Fin.castAdd 24 (Fin.castAdd 20 i) = Fin.castAdd 44 i := by rfl
    rw [hi]
    module
  have h := f4KillingRoot_eq_add_zsmul (Fin.castAdd 44 i) (Fin.castAdd 44 i)
    (Fin.addNat (Fin.castAdd 20 i) 24) (-2) hroot
  apply Weight.ext
  intro x
  have hx := congrFun h x
  change (f4KillingRoot (Fin.addNat (Fin.castAdd 20 i) 24)) x =
    (f4KillingRoot (Fin.castAdd 44 i)) x + (-2 : ℚ) *
      (f4KillingRoot (Fin.castAdd 44 i)) x at hx
  change -(f4KillingRoot (Fin.castAdd 44 i)) x =
    (f4KillingRoot (Fin.addNat (Fin.castAdd 20 i) 24)) x
  rw [hx]
  ring

/-- Two indexed rational Killing roots do not sum to zero unless their pinned labels are
opposite. -/
theorem f4KillingRoot_add_ne_zero_of_ne_opposite (α β : Fin 48)
    (hopp : α ≠ f4OppositeRootIndex β) :
    (f4KillingRoot α : (F4.cartanSubalgebra valid_F4) → ℚ) + f4KillingRoot β ≠ 0 := by
  intro hz
  apply hopp
  apply f4KillingRoot_injective
  rw [f4KillingRoot_f4OppositeRootIndex]
  apply Weight.ext
  intro x
  have hx := congrFun hz x
  simp only [Pi.add_apply, Pi.zero_apply] at hx ⊢
  exact eq_neg_of_add_eq_zero_left hx

/-- If the pinned root string from `β` in direction `α` has no positive step, then the
corresponding modular Chevalley bracket vanishes. -/
theorem f4Modular_lie_rootVector_eq_zero_of_chainTopCoeff_eq_zero (α β : Fin 48)
    (hne : α ≠ β) (hopp : α ≠ f4OppositeRootIndex β)
    (htop : f4SimplyConnectedRootDatum.chainTopCoeff α β = 0) :
    ⁅f4ModularRootVector α, f4ModularRootVector β⁆ = 0 := by
  let H := F4.cartanSubalgebra valid_F4
  let P := rootSystem H
  let E := F4.rationalRootSystemEquiv valid_F4
  let ia := E.indexEquiv (f4RootIndex α)
  let ib := E.indexEquiv (f4RootIndex β)
  let a : Weight ℚ H (F4.lieAlgebra valid_F4) := f4KillingRoot α
  let b : Weight ℚ H (F4.lieAlgebra valid_F4) := f4KillingRoot β
  have ha : a.IsNonZero := by
    simpa only [a, f4KillingRoot] using LieSubalgebra.isNonZero_coe_root ia
  have hb : b.IsNonZero := by
    simpa only [b, f4KillingRoot] using LieSubalgebra.isNonZero_coe_root ib
  have hiab : ia ≠ ib := by
    intro h
    apply hne
    apply f4KillingRoot_injective
    exact congrArg Subtype.val h
  have hneg : P.root ia ≠ -P.root ib := by
    intro h
    apply f4KillingRoot_add_ne_zero_of_ne_opposite α β hopp
    apply funext
    intro x
    have hx := DFunLike.congr_fun h x
    change (f4KillingRoot α : H → ℚ) x = -(f4KillingRoot β : H → ℚ) x at hx
    change (f4KillingRoot α : H → ℚ) x + (f4KillingRoot β : H → ℚ) x = 0
    rw [hx, neg_add_cancel]
  have hlinP : LinearIndependent ℚ ![P.root ia, P.root ib] :=
    RootPairing.IsReduced.linearIndependent P hiab hneg
  have hlin : LinearIndependent ℚ
      ![(a : Module.Dual ℚ H), (b : Module.Dual ℚ H)] := by
    simpa only [P, ia, ib, a, b, rootSystem_root_apply, Weight.toLinear_apply] using hlinP
  have hcoeff := rootSystem_chainCoeffs_eq ha hb hlin
  have hLieTop : chainTopCoeff (a : H → ℚ) b = 0 := by
    rw [← hcoeff.1]
    change P.chainTopCoeff ia ib = 0
    simpa only [P, ia, ib, E, htop] using f4KillingRootSystem_chainTopCoeff α β
  have hroot : rootSpace H ((a : H → ℚ) + b) = ⊥ := by
    by_contra hn
    have hc := (rootSpace_zsmul_add_ne_bot_iff a b ha 1).mp (by
      simpa only [one_zsmul] using hn)
    rw [hLieTop] at hc
    omega
  exact f4Modular_lie_rootVector_eq_zero_of_rootSpace_add_eq_bot α β (by
    simpa only [H, a, b] using hroot)

/-- Opposite integral root vectors bracket to the corresponding integral coroot. -/
theorem f4Integral_lie_rootVector_opposite (α : Fin 48) :
    ⁅f4IntegralRootVector α, f4IntegralRootVector (f4OppositeRootIndex α)⁆ =
      f4IntegralCoroot α := by
  apply Subtype.ext
  change ⁅(f4IntegralRootVector α : F4.lieAlgebra valid_F4),
      (f4IntegralRootVector (f4OppositeRootIndex α) : F4.lieAlgebra valid_F4)⁆ =
    (f4IntegralCoroot α : F4.lieAlgebra valid_F4)
  rw [coe_f4IntegralRootVector, coe_f4IntegralRootVector]
  change ⁅f4ChevalleyRootVector (f4KillingRoot α),
      f4ChevalleyRootVector (f4KillingRoot (f4OppositeRootIndex α))⁆ =
    ((coroot (f4KillingRoot α) : F4.cartanSubalgebra valid_F4) :
      F4.lieAlgebra valid_F4)
  have hop : f4KillingRoot (f4OppositeRootIndex α) = -f4KillingRoot α := by
    exact congrArg
      (fun r : (F4.cartanSubalgebra valid_F4).root =>
        (r : Weight ℚ (F4.cartanSubalgebra valid_F4) (F4.lieAlgebra valid_F4)))
      (f4KillingRootLabel_f4OppositeRootIndex α)
  rw [hop]
  exact f4ChevalleyRootVector_isChevalleySystem.toIsSl2System.lie_neg
    (f4KillingRoot α)
    ((F4.cartanSubalgebra valid_F4).isNonZero_coe_root (f4KillingRootLabel α))

/-- Opposite modular root vectors bracket to the corresponding modular coroot. -/
theorem f4Modular_lie_rootVector_opposite (α : Fin 48) :
    ⁅f4ModularRootVector α, f4ModularRootVector (f4OppositeRootIndex α)⁆ =
      f4ModularCoroot α := by
  rw [f4ModularRootVector_eq, f4ModularRootVector_eq,
    LieAlgebra.ExtendScalars.bracket_tmul, one_mul,
    f4Integral_lie_rootVector_opposite]
  rfl

/-- Recover the Bourbaki node number of a simple Killing root. -/
abbrev f4PinnedSimpleIndex (i : f4KillingBase.support) : Fin 4 :=
  Fin.cast rank_F4 ((F4.lieBasis valid_F4).baseSupportEquiv.symm i)

/-- A Chevalley coordinate is short when it is labelled by a short root or by one of the two
short simple coroots. -/
def f4ChevalleyIndexIsShort : f4ChevalleyIndex → Prop :=
  Sum.elim (fun α => f4Length (f4PinnedRootIndex α) = 1)
    (fun j => f4PinnedSimpleIndex j = 2 ∨ f4PinnedSimpleIndex j = 3)

@[simp] theorem f4ChevalleyIndexIsShort_inl
    (α : (F4.cartanSubalgebra valid_F4).root) :
    f4ChevalleyIndexIsShort (Sum.inl α) ↔
      f4Length (f4PinnedRootIndex α) = 1 := Iff.rfl

@[simp] theorem f4ChevalleyIndexIsShort_inr (j : f4KillingBase.support) :
    f4ChevalleyIndexIsShort (Sum.inr j) ↔
      f4PinnedSimpleIndex j = 2 ∨ f4PinnedSimpleIndex j = 3 := Iff.rfl

/-- The coordinate labels spanning the modular short-root space. -/
def f4ShortChevalleyIndices : Set f4ChevalleyIndex :=
  {i | f4ChevalleyIndexIsShort i}

@[simp] theorem mem_f4ShortChevalleyIndices_iff (i : f4ChevalleyIndex) :
    i ∈ f4ShortChevalleyIndices ↔ f4ChevalleyIndexIsShort i := Iff.rfl

/-- The modular coordinate subspace spanned by short root vectors and the two short simple
coroots. This becomes the characteristic-two short-root ideal after bracket closure is proved. -/
@[expose] def f4ShortRootSubspace : Submodule (ZMod 2) f4ModularChevalleyLieAlgebra :=
  Submodule.span (ZMod 2) (f4ModularChevalleyBasis '' f4ShortChevalleyIndices)

theorem f4ShortRootSubspace_eq_span :
    f4ShortRootSubspace =
      Submodule.span (ZMod 2) (f4ModularChevalleyBasis '' f4ShortChevalleyIndices) := rfl

theorem f4ModularChevalleyBasis_mem_shortRootSubspace {i : f4ChevalleyIndex}
    (hi : f4ChevalleyIndexIsShort i) :
    f4ModularChevalleyBasis i ∈ f4ShortRootSubspace := by
  apply Submodule.subset_span
  exact ⟨i, hi, rfl⟩

theorem f4ModularRootVector_mem_shortRootSubspace (β : Fin 48)
    (hβ : f4Length β = 1) :
    f4ModularRootVector β ∈ f4ShortRootSubspace := by
  rw [f4ModularRootVector_eq_basis]
  apply f4ModularChevalleyBasis_mem_shortRootSubspace
  simpa only [f4ChevalleyIndexIsShort_inl,
    f4PinnedRootIndex_f4KillingRootLabel] using hβ

theorem f4ModularSimpleCoroot_mem_shortRootSubspace (i : Fin F4.rank)
    (hi : Fin.cast rank_F4 i = 2 ∨ Fin.cast rank_F4 i = 3) :
    f4ModularSimpleCoroot i ∈ f4ShortRootSubspace := by
  apply Submodule.subset_span
  refine ⟨Sum.inr ((F4.lieBasis valid_F4).baseSupportEquiv i), ?_, rfl⟩
  change f4PinnedSimpleIndex ((F4.lieBasis valid_F4).baseSupportEquiv i) = 2 ∨
    f4PinnedSimpleIndex ((F4.lieBasis valid_F4).baseSupportEquiv i) = 3
  simpa only [f4PinnedSimpleIndex, Equiv.symm_apply_apply] using hi

/-- Every short-root coroot reduces to the span of the two short simple coroots modulo two. -/
theorem f4ModularCoroot_mem_shortRootSubspace (β : Fin 48) (hβ : f4Length β = 1) :
    f4ModularCoroot β ∈ f4ShortRootSubspace := by
  obtain ⟨k₀, k₁, h₀, h₁⟩ :=
    exists_f4Coroot_longSimple_coordinates_eq_two_mul β hβ
  rw [f4ModularCoroot_eq_sum_simple]
  apply Submodule.sum_mem
  intro i _
  let j : Fin 4 := Fin.cast rank_F4 i
  by_cases hj₀ : j = 0
  · have hz : (f4Coroot β j : ZMod 2) = 0 := by
      rw [hj₀, h₀, Int.cast_mul,
        show ((2 : ℤ) : ZMod 2) = 0 by exact_mod_cast ZMod.natCast_self 2, zero_mul]
    rw [show Fin.cast rank_F4 i = j by rfl, hz, zero_smul]
    exact Submodule.zero_mem _
  by_cases hj₁ : j = 1
  · have hz : (f4Coroot β j : ZMod 2) = 0 := by
      rw [hj₁, h₁, Int.cast_mul,
        show ((2 : ℤ) : ZMod 2) = 0 by exact_mod_cast ZMod.natCast_self 2, zero_mul]
    rw [show Fin.cast rank_F4 i = j by rfl, hz, zero_smul]
    exact Submodule.zero_mem _
  · have hj : j = 2 ∨ j = 3 := by omega
    exact Submodule.smul_mem _ _ (f4ModularSimpleCoroot_mem_shortRootSubspace i hj)

/-- A short--short Chevalley bracket with long-root target vanishes in the modular lattice. This
is the central characteristic-two closure step, obtained by reducing the structural coefficient
of absolute value two rather than by inspecting a bracket table. -/
theorem f4Modular_lie_rootVector_of_short_add_short_eq_long (α β γ : Fin 48)
    (hα : f4Length α = 1) (hβ : f4Length β = 1) (hγ : f4Length γ = 2)
    (h : f4SimplyConnectedRootDatum.root γ =
      f4SimplyConnectedRootDatum.root β + f4SimplyConnectedRootDatum.root α) :
    ⁅f4ModularRootVector α, f4ModularRootVector β⁆ = 0 := by
  obtain ⟨z, hzabs, hlie⟩ :=
    f4_lie_rootVector_of_short_add_short_eq_long α β γ hα hβ hγ h
  have hlieIntegral : ⁅f4IntegralRootVector α, f4IntegralRootVector β⁆ =
      z • f4IntegralRootVector γ := by
    apply Subtype.ext
    change ⁅(f4IntegralRootVector α : F4.lieAlgebra valid_F4),
        (f4IntegralRootVector β : F4.lieAlgebra valid_F4)⁆ =
      z • (f4IntegralRootVector γ : F4.lieAlgebra valid_F4)
    simpa only [coe_f4IntegralRootVector, Int.cast_smul_eq_zsmul] using hlie
  have hzmod : (z : ZMod 2) = 0 := by
    rw [← ZMod.natAbs_mod_two, hzabs]
    exact ZMod.natCast_self 2
  rw [f4ModularRootVector_eq, f4ModularRootVector_eq,
    LieAlgebra.ExtendScalars.bracket_tmul, one_mul, hlieIntegral, TensorProduct.tmul_smul]
  rw [← Int.cast_smul_eq_zsmul (ZMod 2), hzmod, zero_smul]

/-- Bracketing an arbitrary modular root vector with a short-root vector stays in the modular
short-root coordinate space. -/
theorem f4Modular_lie_rootVector_mem_shortRootSubspace (α β : Fin 48)
    (hβ : f4Length β = 1) :
    ⁅f4ModularRootVector α, f4ModularRootVector β⁆ ∈ f4ShortRootSubspace := by
  let H := F4.cartanSubalgebra valid_F4
  by_cases hsum :
      (f4KillingRoot α : H → ℚ) + (f4KillingRoot β : H → ℚ) = 0
  · have hweight : f4KillingRoot α = -f4KillingRoot β := by
      apply Weight.ext
      intro y
      have hy := congrFun hsum y
      simp only [Pi.add_apply, Pi.zero_apply] at hy
      exact eq_neg_of_add_eq_zero_left hy
    have hlabel : f4KillingRootLabel α = -f4KillingRootLabel β := by
      apply Subtype.ext
      exact hweight
    have hindex : α = f4OppositeRootIndex β := by
      rw [← f4PinnedRootIndex_f4KillingRootLabel α]
      exact congrArg f4PinnedRootIndex hlabel
    rw [hindex, ← lie_skew, f4Modular_lie_rootVector_opposite]
    exact Submodule.neg_mem _ (f4ModularCoroot_mem_shortRootSubspace β hβ)
  by_cases hbot : rootSpace H
      ((f4KillingRoot α : H → ℚ) + (f4KillingRoot β : H → ℚ)) = ⊥
  · rw [f4Modular_lie_rootVector_eq_zero_of_rootSpace_add_eq_bot α β hbot]
    exact Submodule.zero_mem _
  · have hadd : (f4KillingRoot β : H → ℚ) + (f4KillingRoot α : H → ℚ) =
        (f4KillingRoot α : H → ℚ) + (f4KillingRoot β : H → ℚ) := add_comm _ _
    have hroot : rootSpace H
        ((f4KillingRoot β : H → ℚ) + (f4KillingRoot α : H → ℚ)) ≠ ⊥ := by
      rw [hadd]
      exact hbot
    let δ : Weight ℚ H (F4.lieAlgebra valid_F4) :=
      ⟨(f4KillingRoot β : H → ℚ) + (f4KillingRoot α : H → ℚ), hroot⟩
    have hδ : δ.IsNonZero := by
      intro hz
      apply hsum
      change (f4KillingRoot β : H → ℚ) + (f4KillingRoot α : H → ℚ) = 0 at hz
      exact hadd.symm.trans hz
    let r : H.root := ⟨δ, by simpa only [LieSubalgebra.root, Finset.mem_filter,
      Finset.mem_univ, true_and] using hδ⟩
    let γ : Fin 48 := f4PinnedRootIndex r
    have hγweight : f4KillingRoot γ = δ := by
      exact congrArg
        (fun s : H.root => (s : Weight ℚ H (F4.lieAlgebra valid_F4)))
        (f4KillingRootLabel_f4PinnedRootIndex r)
    have hγ : f4SimplyConnectedRootDatum.root γ =
        f4SimplyConnectedRootDatum.root β + f4SimplyConnectedRootDatum.root α := by
      apply f4Root_eq_add_of_f4KillingRoot_eq_add
      exact congrArg DFunLike.coe hγweight
    rcases f4Length_eq_one_or_eq_two γ with hγshort | hγlong
    · obtain ⟨z, _, hlie⟩ := f4Modular_lie_rootVector_of_add α β γ hγ
      rw [hlie]
      exact Submodule.smul_mem _ _
        (f4ModularRootVector_mem_shortRootSubspace γ hγshort)
    · rcases f4Length_eq_one_or_eq_two α with hαshort | hαlong
      · rw [f4Modular_lie_rootVector_of_short_add_short_eq_long α β γ
          hαshort hβ hγlong hγ]
        exact Submodule.zero_mem _
      · have hγshort :=
          f4_n_eq_one_and_pairing_eq_neg_one_and_length_eq_one_of_short_add_nsmul_long
            α β γ 1 hαlong hβ (by omega) (by
          simpa using hγ)
        omega

/-- Bracketing an arbitrary modular root vector with either short simple coroot stays in the
modular short-root coordinate space. Long-root coefficients vanish by length symmetry modulo
two. -/
theorem f4Modular_lie_rootVector_simpleCoroot_mem_shortRootSubspace
    (α : Fin 48) (i : Fin F4.rank)
    (hi : Fin.cast rank_F4 i = 2 ∨ Fin.cast rank_F4 i = 3) :
    ⁅f4ModularRootVector α, f4ModularSimpleCoroot i⁆ ∈ f4ShortRootSubspace := by
  rw [← lie_skew, f4Modular_lie_simpleCoroot_rootVector]
  rcases f4Length_eq_one_or_eq_two α with hαshort | hαlong
  · exact Submodule.neg_mem _ (Submodule.smul_mem _ _
      (f4ModularRootVector_mem_shortRootSubspace α hαshort))
  · let j : Fin 4 := Fin.cast rank_F4 i
    let s : Fin 48 := Fin.castAdd 44 j
    have hs : f4Length s = 1 := by
      rcases hi with hi | hi
      · simp only [s, f4Length_castAdd, rootLength_F4, j, hi]
        norm_num
      · simp only [s, f4Length_castAdd, rootLength_F4, j, hi]
        norm_num
    have hsym := f4Length_mul_pairing_comm s α
    rw [hs, hαlong, one_mul] at hsym
    have heven : f4SimplyConnectedRootDatum.pairing α s =
        2 * f4SimplyConnectedRootDatum.pairing s α := hsym
    have hz : (f4SimplyConnectedRootDatum.pairing α s : ZMod 2) = 0 := by
      rw [heven, Int.cast_mul,
        show ((2 : ℤ) : ZMod 2) = 0 by exact_mod_cast ZMod.natCast_self 2, zero_mul]
    rw [show Fin.castAdd 44 (Fin.cast rank_F4 i) = s by rfl, hz, zero_smul, neg_zero]
    exact Submodule.zero_mem _

/-- Modular simple coroots commute. -/
theorem f4Modular_lie_simpleCoroot_simpleCoroot_eq_zero (i j : Fin F4.rank) :
    ⁅f4ModularSimpleCoroot i, f4ModularSimpleCoroot j⁆ = 0 := by
  have hlieIntegral : ⁅f4IntegralSimpleCoroot i, f4IntegralSimpleCoroot j⁆ = 0 := by
    apply Subtype.ext
    change ⁅(f4IntegralSimpleCoroot i : F4.lieAlgebra valid_F4),
        (f4IntegralSimpleCoroot j : F4.lieAlgebra valid_F4)⁆ = 0
    simp only [f4IntegralSimpleCoroot, f4ChevalleyBasis,
      IsChevalleySystem.coe_rootSimpleCorootBasis_inr]
    exact lie_coroot_coroot_eq_zero _ _
  rw [f4ModularSimpleCoroot_eq, f4ModularSimpleCoroot_eq,
    LieAlgebra.ExtendScalars.bracket_tmul, one_mul, hlieIntegral,
    TensorProduct.tmul_zero]

theorem f4Modular_lie_simpleCoroot_rootVector_mem_shortRootSubspace
    (i : Fin F4.rank) (α : Fin 48) (hα : f4Length α = 1) :
    ⁅f4ModularSimpleCoroot i, f4ModularRootVector α⁆ ∈ f4ShortRootSubspace := by
  rw [f4Modular_lie_simpleCoroot_rootVector]
  exact Submodule.smul_mem _ _ (f4ModularRootVector_mem_shortRootSubspace α hα)

private theorem f4Modular_lie_basis_inl_inl_mem_shortRootSubspace
    (α β : (F4.cartanSubalgebra valid_F4).root)
    (hβ : f4ChevalleyIndexIsShort (Sum.inl β)) :
    ⁅f4ModularChevalleyBasis (Sum.inl α),
      f4ModularChevalleyBasis (Sum.inl β)⁆ ∈ f4ShortRootSubspace := by
  rw [f4ModularChevalleyBasis_inl_eq_rootVector,
    f4ModularChevalleyBasis_inl_eq_rootVector]
  exact f4Modular_lie_rootVector_mem_shortRootSubspace
    (f4PinnedRootIndex α) (f4PinnedRootIndex β)
    ((f4ChevalleyIndexIsShort_inl β).mp hβ)

private theorem f4Modular_lie_basis_inl_inr_mem_shortRootSubspace
    (α : (F4.cartanSubalgebra valid_F4).root) (b : f4KillingBase.support)
    (hbshort : f4ChevalleyIndexIsShort (Sum.inr b)) :
    ⁅f4ModularChevalleyBasis (Sum.inl α),
      f4ModularChevalleyBasis (Sum.inr b)⁆ ∈ f4ShortRootSubspace := by
  let k : Fin F4.rank := (F4.lieBasis valid_F4).baseSupportEquiv.symm b
  have hk : Fin.cast rank_F4 k = 2 ∨ Fin.cast rank_F4 k = 3 := by
    simpa only [k, f4PinnedSimpleIndex] using
      (f4ChevalleyIndexIsShort_inr b).mp hbshort
  have hb : f4ModularChevalleyBasis (Sum.inr b) = f4ModularSimpleCoroot k := by
    symm
    simpa only [k, Equiv.apply_symm_apply] using f4ModularSimpleCoroot_eq_basis k
  rw [f4ModularChevalleyBasis_inl_eq_rootVector, hb]
  exact f4Modular_lie_rootVector_simpleCoroot_mem_shortRootSubspace
    (f4PinnedRootIndex α) k hk

private theorem f4Modular_lie_basis_inr_inl_mem_shortRootSubspace
    (a : f4KillingBase.support) (β : (F4.cartanSubalgebra valid_F4).root)
    (hβ : f4ChevalleyIndexIsShort (Sum.inl β)) :
    ⁅f4ModularChevalleyBasis (Sum.inr a),
      f4ModularChevalleyBasis (Sum.inl β)⁆ ∈ f4ShortRootSubspace := by
  let k : Fin F4.rank := (F4.lieBasis valid_F4).baseSupportEquiv.symm a
  have ha : f4ModularChevalleyBasis (Sum.inr a) = f4ModularSimpleCoroot k := by
    symm
    simpa only [k, Equiv.apply_symm_apply] using f4ModularSimpleCoroot_eq_basis k
  have hb := f4ModularChevalleyBasis_inl_eq_rootVector β
  rw [ha, hb]
  exact f4Modular_lie_simpleCoroot_rootVector_mem_shortRootSubspace k
    (f4PinnedRootIndex β) ((f4ChevalleyIndexIsShort_inl β).mp hβ)

private theorem f4Modular_lie_basis_inr_inr_mem_shortRootSubspace
    (a b : f4KillingBase.support) :
    ⁅f4ModularChevalleyBasis (Sum.inr a),
      f4ModularChevalleyBasis (Sum.inr b)⁆ ∈ f4ShortRootSubspace := by
  let k : Fin F4.rank := (F4.lieBasis valid_F4).baseSupportEquiv.symm a
  let l : Fin F4.rank := (F4.lieBasis valid_F4).baseSupportEquiv.symm b
  have ha : f4ModularChevalleyBasis (Sum.inr a) = f4ModularSimpleCoroot k := by
    symm
    simpa only [k, Equiv.apply_symm_apply] using f4ModularSimpleCoroot_eq_basis k
  have hb : f4ModularChevalleyBasis (Sum.inr b) = f4ModularSimpleCoroot l := by
    symm
    simpa only [l, Equiv.apply_symm_apply] using f4ModularSimpleCoroot_eq_basis l
  rw [ha, hb, f4Modular_lie_simpleCoroot_simpleCoroot_eq_zero]
  exact Submodule.zero_mem _

/-- A Chevalley basis vector brackets every distinguished short Chevalley basis vector back into
the short coordinate space. -/
theorem f4Modular_lie_basis_mem_shortRootSubspace (i j : f4ChevalleyIndex)
    (hj : f4ChevalleyIndexIsShort j) :
    ⁅f4ModularChevalleyBasis i, f4ModularChevalleyBasis j⁆ ∈
      f4ShortRootSubspace := by
  rcases i with α | a <;> rcases j with β | b
  · exact f4Modular_lie_basis_inl_inl_mem_shortRootSubspace α β hj
  · exact f4Modular_lie_basis_inl_inr_mem_shortRootSubspace α b hj
  · exact f4Modular_lie_basis_inr_inl_mem_shortRootSubspace a β hj
  · exact f4Modular_lie_basis_inr_inr_mem_shortRootSubspace a b

/-- The modular short-root coordinate space is stable under the bracket with every element of the
reduced Chevalley Lie algebra. -/
theorem f4ShortRootSubspace_lie_mem (x : f4ModularChevalleyLieAlgebra)
    {y : f4ModularChevalleyLieAlgebra} (hy : y ∈ f4ShortRootSubspace) :
    ⁅x, y⁆ ∈ f4ShortRootSubspace := by
  have hx := f4ModularChevalleyBasis.mem_span x
  rw [f4ShortRootSubspace_eq_span] at hy ⊢
  induction hx, hy using Submodule.span_induction₂ with
  | mem_mem x y hx hy =>
      rcases hx with ⟨i, rfl⟩
      rcases hy with ⟨j, hj, rfl⟩
      apply f4Modular_lie_basis_mem_shortRootSubspace i j
      exact (mem_f4ShortChevalleyIndices_iff j).mp hj
  | zero_left =>
      rw [zero_lie]
      exact Submodule.zero_mem _
  | zero_right x _ =>
      change (LieAlgebra.ad (ZMod 2) f4ModularChevalleyLieAlgebra x) 0 ∈ _
      rw [map_zero]
      exact Submodule.zero_mem _
  | add_left _ _ _ _ _ _ h₁ h₂ =>
      rw [add_lie]
      exact Submodule.add_mem _ h₁ h₂
  | add_right x y z _ _ _ h₁ h₂ =>
      change (LieAlgebra.ad (ZMod 2) f4ModularChevalleyLieAlgebra x) (y + z) ∈ _
      rw [map_add]
      exact Submodule.add_mem _ h₁ h₂
  | smul_left r _ _ _ _ h =>
      rw [smul_lie]
      exact Submodule.smul_mem _ r h
  | smul_right r x y _ _ h =>
      change (LieAlgebra.ad (ZMod 2) f4ModularChevalleyLieAlgebra x) (r • y) ∈ _
      rw [map_smul]
      exact Submodule.smul_mem _ r h

/-- The characteristic-two short-root coordinate space as a Lie ideal in the reduced integral
Chevalley algebra. -/
@[expose] noncomputable def f4ShortRootLieIdeal :
    LieIdeal (ZMod 2) f4ModularChevalleyLieAlgebra :=
  { f4ShortRootSubspace with
    lie_mem := fun {x _y} hy => f4ShortRootSubspace_lie_mem x hy }

@[simp] theorem mem_f4ShortRootLieIdeal_iff {x : f4ModularChevalleyLieAlgebra} :
    x ∈ f4ShortRootLieIdeal ↔ x ∈ f4ShortRootSubspace := by
  change x ∈ f4ShortRootSubspace ↔ x ∈ f4ShortRootSubspace
  rfl

end

end TauCeti.DynkinType
